name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 3. Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release --base-href /Polygons-Wave-animation/

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          user_name: GitVNS
          user_email: GitVNS@users.noreply.github.com
